workflow:
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /\[skip pipeline\]/
      when: never
    - if: $CI_MERGE_REQUEST_ID
      when: never
    - when: always

## Pipeline stages ##
stages:
# - compile
- find-cluster
- deploy
- pa-was-test
- integration-test
- chaos
- cleanup

## Global environment variables ##
variables:
  DELETE_ENV_AFTER_PIPELINE: 'true'
  K8S_DEPLOY_TOOLS: docker.corp.pingidentity.com:5000/platform-pipeline/k8s-deploy-tools@sha256:b72cb43513f083d5ab77248cf70491444e3bbc5d5bda0c982502ad5113ca88d6
  SHARED_CI_SCRIPTS_DIR: "/ci-scripts"
  BRANCH_SKIP_TESTS: >
    pingaccess/08-artifact-test.sh
    pingdelegator/01-admin-user-login.sh
    pingdirectory/03-backup-restore.sh
    pingdirectory/08-test-http-connection-handler.sh

## Compile stage ##
# compile:
#  stage: compile
#  tags:
#    - default-gitlab-runner
#  image: ${K8S_DEPLOY_TOOLS}
#  script:
#    - ${SHARED_CI_SCRIPTS_DIR}/k8s/compile/compile.sh

## Find cluster stage ##
find-cluster:
  stage: find-cluster
  tags:
    - default-gitlab-runner
  image: ${K8S_DEPLOY_TOOLS}
  script:
    - ${SHARED_CI_SCRIPTS_DIR}/k8s/deploy/find_cluster.sh
  artifacts:
    reports:
      dotenv: cluster.env

## Deploy stage ##
deploy:
  stage: deploy
  tags:
    - default-gitlab-runner
  image: ${K8S_DEPLOY_TOOLS}
  script:
    - echo "ENV_TYPE ${ENV_TYPE}"
    # - if test -n "${ENV_TYPE}"; then export ENV_TYPE=${ENV_TYPE}; fi
    - ${SHARED_CI_SCRIPTS_DIR}/k8s/deploy/deploy.sh
  dependencies:
    - find-cluster

## Integration Test stage ##

## PA-WAS stage ##
pa-was-integration-tests:
  stage: pa-was-test
  tags:
    - default-gitlab-runner
  image: ${K8S_DEPLOY_TOOLS}
  script:
    - ${SHARED_CI_SCRIPTS_DIR}/test/run-tests.sh pingaccess-was
  dependencies:
    - find-cluster

################################################
# All integration tests defined to run on the  #
# traditionally deployed P1AS                  #
################################################
.all-tests: &all-tests
  - pingdirectory
  - pingdelegator
  - pingfederate
  - pingaccess
  - pingcloud-services
  - pingcentral
  - pingdatasync
  - common
  - monitoring
  - health
  - pingone

#################################################
# All integration tests defined to run on the  #
# traditionally deployed P1AS                  #
################################################
.schedule-tests: &schedule-tests
  - pingdirectory
  - pingdelegator
  - pingfederate
  - pingaccess
  - pingcloud-services
  - pingdatasync
  - common
  - monitoring
  - health
  - pingone

################################################
# All integration tests defined to run on the  #
# traditionally deployed P1AS                  #
################################################
.chub-tests: &chub-tests
  - pingcloud-services
  - pingcentral
  - common
  - monitoring
  - health
  
.integration-tests-base:
  variables:
    TEST: ""
  stage: integration-test
  tags:
    - default-gitlab-runner
  image: ${K8S_DEPLOY_TOOLS}
  script:
    - echo "ENV_TYPE ${ENV_TYPE}"
    # - if test -n "${ENV_TYPE}"; then export ENV_TYPE=${ENV_TYPE}; fi
    - ${SHARED_CI_SCRIPTS_DIR}/test/run-tests.sh ${TEST}
  dependencies:
    - find-cluster
  artifacts:
    name: "integration_test_logs"
    paths:
      - tests/pingone/latest_logs/
    when: on_failure

integration-tests:
  extends: .integration-tests-base
  variables:
    TEST: ${TEST}
  parallel:
    matrix:
      - TEST: *all-tests
  only:
    variables:
      - $ENV_TYPE == "null"
      - $CI_PIPELINE_SOURCE != "schedule"

integration-tests-scheduled-pipeline:
  extends: .integration-tests-base
  variables:
    TEST: ${TEST}
  parallel:
    matrix:
      - TEST: *schedule-tests
  only:
    variables:
      - $ENV_TYPE != "customer-hub"
      - $CI_PIPELINE_SOURCE == "schedule"

integration-tests-chub:
  extends: .integration-tests-base
  variables:
    TEST: ${TEST}
  parallel:
    matrix:
      - TEST: *chub-tests
  only:
    variables:
      - $ENV_TYPE == "customer-hub"
      
## Chaos testing stage ##
chaos-tests:
  stage: chaos
  tags:
    - default-gitlab-runner
  image: ${K8S_DEPLOY_TOOLS}
  script:
    - echo "ENV_TYPE ${ENV_TYPE}"
    # - if test -n "${ENV_TYPE}"; then export ENV_TYPE=${ENV_TYPE}; fi
    - ${SHARED_CI_SCRIPTS_DIR}/test/run-tests.sh chaos
  dependencies:
    - find-cluster

## Cleanup stage ##
cleanup:
  stage: cleanup
  tags:
    - default-gitlab-runner
  image: ${K8S_DEPLOY_TOOLS}
  script:
    - ${SHARED_CI_SCRIPTS_DIR}/k8s/cleanup/teardown.sh
  dependencies:
    - find-cluster