kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: elastic-stack-logging

resources:
- configs
- security_configs
- pdb.yaml
- rbac.yaml
- service.yaml
- sts.yaml
- index-templates
- storageclass.yaml
- certs.yaml
- ism-policies
- alerts
- notifications
- bootstrap.yaml

patchesStrategicMerge:

- |-
  # Add IRSA role annotation to opensearch service account
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: logstash-elastic
    namespace: elastic-stack-logging
    annotations:
      purpose: service-account-for-opensearch
      ${IRSA_OPENSEARCH_ANNOTATION_KEY_VALUE}

