apiVersion: v1
kind: ConfigMap
metadata:
  name: pingdirectory-export-ldif
data:
  export-ldif-data.sh: |-
    #!/bin/sh

    # Install kubectl
    curl -sS https://storage.googleapis.com/kubernetes-release/release/"${KUBECTL_VERSION}"/bin/linux/amd64/kubectl -o /tmp/kubectl
    chmod +x /tmp/kubectl

    NUM_REPLICAS=$(/tmp/kubectl get statefulset "${K8S_STATEFUL_SET_NAME}" -o jsonpath='{.spec.replicas}')

    START=0
    END=$((${NUM_REPLICAS} - 1))

    LDIF_FILES=
    test -z "${BACKUP_RESTORE_POD}" && SERVER="${K8S_STATEFUL_SET_NAME}-0" || SERVER="${BACKUP_RESTORE_POD}"
    SCRIPT="${HOOKS_DIR}"/90-export-ldif-s3.sh
    LOG_FILE=/tmp/upload.log

    echo "Uploading LDIF_FILES on server ${SERVER}"
    /tmp/kubectl exec "${SERVER}" -c pingdirectory -- sh -c "test -x ${SCRIPT} && ${SCRIPT}">"${LOG_FILE}"

    if test ${?} -eq 0; then
      # Sending logs to STDOUT
      cat ${LOG_FILE}
      LDIF_FILE=$(tail -1 "${LOG_FILE}")
      test -z "${LDIF_FILES}" && LDIF_FILES="${LDIF_FILE}" || LDIF_FILES="${LDIF_FILES} ${LDIF_FILE}"
    else
      echo "Error occurred while uploading LDIF_FILES on server ${SERVER}"
      exit 1
    fi
