apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipelines
  labels:
    app: logstash-elastic
data:
  pipelines.yml: |
    - pipeline.id: cloudwatch
      path.config: "/usr/share/logstash/pipeline/cloudwatch"