kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- storage.yaml
- logstash.yaml
- logstash_pipelines
- hpa.yaml
- logstash-search-template.yaml

patchesStrategicMerge:

- |-
  # Add IRSA role annotation to logstash-elastic service account
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: logstash-elastic
    namespace: elastic-stack-logging
    annotations:
      purpose: service-account-for-logstash-elastic
      ${IRSA_LOGSTASH_ANNOTATION_KEY_VALUE}