---
apiVersion: batch/v1
kind: Job
metadata:
  namespace: elastic-stack-logging
  name: index-migration
spec:
  template:
    spec:
      containers:
      - name: index-migration
        image: 705370621539.dkr.ecr.us-west-2.amazonaws.com/pingcloud-monitoring/index-migration:PDO-5145
        imagePullPolicy: Always
        workingDir: /scripts
        #command: ["python3", 'index-migration.py']
        command: ["sleep", '5000']
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
          allowPrivilegeEscalation: false
        env:
        - name: OPENSEARCH_HOST
          value: "opensearch-cluster-master"
        - name: OPENSEARCH_PORT
          value: "9200"
        - name: OPENSEARCH_USER_NAME
          value: "indexmigraion"
        - name: OPENSEARCH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: os-indexmigration-password
              key: password
        - name: ELASTICSEARCH_HOST
          value: "elasticsearch"
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: STATUS_CHECK_SECONDS
          value: "30"
        resources:
          requests:
            memory: "256Mi"
            cpu: "300m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      restartPolicy: OnFailure

---
apiVersion: v1
data:
  password: Ym5nVjg1cVtOUnN0PUUySyYjdHc=
kind: Secret
metadata:
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
  name: os-indexmigration-password
  namespace: elastic-stack-logging
type: Opaque